[build]
  Functions = "functions"
  publish = "public"
  command = "npm run build"


# Proxy puttr seaches to my search lambda
[[redirects]]
  from = "/puttr/api"
  to = "/.netlify/functions/puttr"
  status = 200

